name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -v .

    - name: Run tests
      # LONG_WAIT notifies the tests to not worry near as much about
      # perormance of the sockets, rather the messages. This is set 
      # to false on a regular machine
      run: |
        export LONG_WAIT=20
        go test -v .

    - name: Generate Coverage
      run: |
        export LONG_WAIT=20
        go test -covermode atomic -coverprofile=coverage.cov .

    - name: Send Coverage Report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.cov